baseURL = "https://jean0t.github.io/"
languageCode = 'en-us'
title = "Jean0t Blog"
taxonomy = ["HTML", "RSS"]
pygmentsStyle = "github-dark"

[[module.imports]]
path = "hugo-theme-stack"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
